"""create jobs, todos, approval_tokens

Revision ID: 630e58998aa5
Revises:
Create Date: 2026-07-25 00:09:59.582502

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "630e58998aa5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_tokens",
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("todo_id", sa.String(length=64), nullable=False),
        sa.Column("asset_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("used_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        "ix_approval_tokens_expires_at", "approval_tokens", ["expires_at"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("preview", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_created_at", "jobs", ["created_at"], unique=False)
    op.create_table(
        "todos",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.Column("checked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("asset_path", sa.Text(), nullable=True),
        sa.Column("asset_name", sa.Text(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("rejected", sa.Boolean(), nullable=False),
        sa.Column("reject_comment", sa.Text(), nullable=True),
        sa.Column("drive_file_id", sa.String(length=128), nullable=True),
        sa.Column("drive_uploaded_at", sa.Float(), nullable=True),
        sa.Column("drive_upload_job_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_todos_created_at", "todos", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_todos_created_at", table_name="todos")
    op.drop_table("todos")
    op.drop_index("ix_jobs_created_at", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_approval_tokens_expires_at", table_name="approval_tokens")
    op.drop_table("approval_tokens")
    # ### end Alembic commands ###
