"""create models and instagram_accounts

Revision ID: c424ff3f1580
Revises: 630e58998aa5
Create Date: 2026-07-27 01:28:14.123407

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c424ff3f1580"
down_revision: str | None = "630e58998aa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("profile_picture_path", sa.Text(), nullable=True),
        sa.Column("profile_picture_name", sa.Text(), nullable=True),
        sa.Column("onlyfans_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_models_created_at", "models", ["created_at"], unique=False)
    op.create_table(
        "instagram_accounts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_instagram_accounts_model_id",
        "instagram_accounts",
        ["model_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_instagram_accounts_model_id", table_name="instagram_accounts")
    op.drop_table("instagram_accounts")
    op.drop_index("ix_models_created_at", table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
